apiVersion: v1
kind: Service
metadata:
  name: streamlit-service
  labels:
    app: streamlit
spec:
  type: NodePort
  selector:
    app: streamlit
  ports:
  - protocol: TCP
    port: 8501
    targetPort: 8501
    nodePort: 31300  # This maps to the hostPort configured in kind-config.yml
    name: http
